matrix:
  include:
    - language: java
      services:
        - postgresql
      env:
        - PGPORT=5432
      jdk:
        - oraclejdk8
      before_script:
        - psql -f 'api/docker/postgresql/init.sql' -U postgres
      script:
        - cd api/
        - ./gradlew check
        - ./gradlew jacocoTestReport

    - language: node_js
      node_js:
        - "10.8.0"
      script:
        - cd ui/
        - yarn install

after_success:
  - bash <(curl -s https://codecov.io/bash)
