matrix:
  include:
    - name: "Backend"
      language: java
      services:
        - docker
      env:
        global:
          - PGPORT=5432
          - GENERATE_SCHEMA=false
      jdk:
        - oraclejdk8
      before_cache:
        - rm -f  $HOME/api/.gradle/caches/modules-2/modules-2.lock
        - rm -fr $HOME/api/.gradle/caches/*/plugin-resolution/
      cache:
        directories:
          - $HOME/api/.gradle/caches/
          - $HOME/api/.gradle/wrapper/
      before_install:
        - sudo /etc/init.d/postgresql stop
        - cd api/docker/
        - docker-compose up -d
        - cd ../../
      script:
        - cd api/
        - ./gradlew check
        - ./gradlew jacocoTestReport
        - ls -A $HOME/api/.gradle/
        - ls -A $HOME/.gradle/
    - name: "Frontend"
      language: node_js
      node_js:
        - "10.8.0"
      cache:
        directories:
          - ui/node_modules
      script:
        - cd ui/
        - yarn install
        - yarn eslint
        - yarn stylelint
        - yarn build
        - yarn test
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
    - master
