server:
  port: 8080

spring:
  application.name: the-hub
  datasource:
    url: jdbc:postgresql://localhost:5432/codeloop
    username: codeloop
    password: codeloop
  jpa:
    open-in-view: true
    hibernate.ddl-auto: validate
    properties.hibernate.enable_lazy_load_no_trans: true
    properties.hibernate.event.merge.entity_copy_observer: allow
    properties.hibernate.format_sql: true
    properties.hibernate.use_sql_comments: true
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  jackson.default-property-inclusion: non_null

logging:
  level:
    eu.codeloop: DEBUG
    org.jooq: INFO
    org.springframework.web.client: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE


thehub:
  scheduling.enable: false
  sync:
    # todo
#    domains: https://hub.no, https://thehub.dk, https://thehub.se, https://thehub.fi
    domains: http://localhost:${wiremock.server.port}
    scheduling.fixedRate-in-milliseconds: 900000
  job.approved-at-default: 2000-01-01T00:00:00.000Z

spring.data.web.pageable.one-indexed-parameters: true
