server:
  port: 8080

spring:
  application.name: the-hub
  datasource:
    url: jdbc:postgresql://localhost:5432/softwareberg
    username: softwareberg
    password: softwareberg
  jpa:
    open-in-view: true
    hibernate.ddl-auto: validate
    properties.hibernate.format_sql: true
    properties.hibernate.use_sql_comments: true
    properties.org.hibernate.envers.store_data_at_delete: true
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  jackson.default-property-inclusion: non_empty

logging:
  level:
    com.softwareberg: DEBUG
    org.springframework.web.client: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

thehub:
  schdeuling:
    enable: true
    sync.fixedRate-in-milliseconds: 900000
