server:
  port: 8080

spring:
  application.name: the-hub
  datasource:
    url: jdbc:postgresql://localhost:5432/softwareberg
    username: softwareberg
    password: softwareberg
  jpa:
    open-in-view: true
    hibernate.ddl-auto: validate
    properties.hibernate.enable_lazy_load_no_trans: true
    properties.hibernate.event.merge.entity_copy_observer: allow
    properties.hibernate.format_sql: true
    properties.hibernate.use_sql_comments: true
    properties.hibernate.jdbc.lob.non_contextual_creation: true
  jackson.default-property-inclusion: non_null

logging:
  level:
    com.softwareberg: DEBUG
    org.jooq: INFO
    org.springframework.web.client: DEBUG
    org.springframework.web.servlet: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestResponseBodyMethodProcessor: INFO
    org.hibernate.SQL: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: INFO


thehub:
  scheduling.enable: false
  sync:
    domains: hub.no, thehub.dk, thehub.se, thehub.fi
    scheduling.fixedRate-in-milliseconds: 900000
